branch-defaults:
  master:
    environment: LowCost-env
environment-defaults:
  LowCost-env:
    branch: null
    repository: null
global:
  application_name: Likes2ChillWebApp
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2016.09 v2.3.1 running Tomcat 8 Java 8
  default_region: us-west-2
  profile: arash
  sc: git
